name: lineage microg random

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

# push:
#   branches: [ master ]
  schedule:
    - cron: '30 17 * * *'
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Installing github-release
      run: |
        go install github.com/github-release/github-release@latest > /dev/null 2>&1

    - name: Change PAT and running script
      env:
        MY_PAT: ${{ secrets.MY_PAT }}
      run: |
        find . -iname "assorted_lineage.sh"
        readlink -f assorted_lineage.sh
        sed -i "s/github_pat_CHANGEME/$MY_PAT/g" assorted_lineage.sh
        sudo apt-get install -y rename > /dev/null 2>&1
        chmod +x assorted_lineage.sh
        echo "Running script now ............"
        ./assorted_lineage.sh
        #ls -al _release/bin

